version: 1
jobs:
 build:
   machine: true
   steps:
     - checkout
     # start proprietary DB using private Docker image
     # with credentials stored in the UI
     # build the application image
     
     #- run: docker build -t emcc -f ./emcc/Dockerfile .
     - run: 
        command: |
          cd ./emcc
          ls
          pwd
          docker build -t emcc .

       
