name: Emcc Build CI

on: 
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'     
        required: true
        default: 'warning'
      tags:
        description: 'Test scenario tags'  
      
jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: |
        cd ./emcc
        docker build -t emcc .
        
    - name: Run Docker
      run: |
        mkdir build
        cd build
        docker run -t emcc
    
    - name: test
      run: |
        pwd
        ls
        ls build
        ls build/output
        
    - name: Archive Output
      uses: actions/upload-artifact@v2
      with:
        name: emcc output
        path: build/output 
