name: Ubuntu Build CI

on:
  workflow_dispatch:
    inputs:
      profile:
        description: 'Build profile'
        type: choice
        options:
          - standard
          - osdi
        default: standard
        required: true
      logLevel:
        description: 'Log level'     
        required: true
        default: 'warning'
  schedule:
    - cron: '0 7 * * 0'  # Runs at 5:00 AM UTC every Sunday

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v6
    - name: Build ngspice
      run: |
        cd ./linux
        chmod +x build.sh
        if [ "${{ github.event.inputs.profile }}" = "osdi" ]; then
          ./build.sh --osdi
        else
          ./build.sh
        fi
        
    - name: Archive standard output
      if: github.event.inputs.profile != 'osdi'
      uses: actions/upload-artifact@v7
      with:
        name: linux-standard
        path: linux/ngspice
    - name: Archive OSDI output
      if: github.event.inputs.profile == 'osdi'
      uses: actions/upload-artifact@v7
      with:
        name: linux-osdi
        path: linux/build/osdi/
