name: Ubuntu Build CI

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'     
        required: true
        default: 'warning'
  schedule:
    - cron: '0 7 * * 0'  # Runs at 5:00 AM UTC every Sunday

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v6
    - name: Build ngspice
      run: |
        cd ./linux
        chmod +x build.sh
        ./build.sh
        
    - name: Archive Output
      uses: actions/upload-artifact@v7
      with:
        name: linux output
        path: linux/ngspice
