# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Mirror CI

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest


    steps:
    #- uses: actions/checkout@v2
    - name: Mirror
      run: |
        git clone --mirror https://git.code.sf.net/p/ngspice/ngspice.git
        cd ngspice.git
        git remote set-url --push origin https://github.com/danchitnis/ngspice-sf-mirror
        echo -e 'git clone completed'
        git config --global user.name danchitnis
        git config --global user.email 'danchitnis@users.noreply.github.com'
        git remote set-url origin https://x-access-token:${{ secrets.ACCESS_TOKEN }}@github.com/danchitnis/ngspice-sf-mirror
        echo -e 'git setup completed'
        git fetch -p origin
        git push --mirror
        echo -e 'git push completed'


